<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>SlideShowLoader</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SlideShowInterfaces\SlideShowInterfaces.vbproj" />
    <ProjectReference Include="..\SlideShowLogging\SlideShowLogging.vbproj" />
  </ItemGroup>

</Project>
